### ISSUE TITLE
never ending turning wheel on save button after enabling

### ISSUE THREAD

**Issue by lebajez** [awe-source/OctoPrint-SkipTo#2]
**octoprint Version 1.10.2**

- enabling plugin causes _save button_ to a _never ending_ turning wheel.

- no other settings can be modified.

- after disabling, every thing works fine.

- tested uninstall/install and disabling/re enabling it, which does not solve the issue.

**Comment by awe-source** [comment]
hi,
can you try
a. uninstall, restart server/octoprint, install
b. CTL+F5 (the "no settings can be modified" is a javascript bug that was fixed, but JS can be "sticky")
c. trying to install directly from the url: (which is, as *I* understand it, where its SUPPOSED to come from...) and then "Plugin Manager > Get More > install from url - https://github.com/awe-source/OctoPrint-SkipTo/archive/master.zip

![image](https://github.com/user-attachments/assets/5f5cda24-5a0e-4443-8d30-6762c79afeb0)

**Comment by lebajez** [comment]
> hi, can you try a. uninstall, restart server/octoprint, install b. CTL+F5 (the "no settings can be modified" is a javascript bug that was fixed, but JS can be "sticky") c. trying to install directly from the url: (which is, as _I_ understand it, where its SUPPOSED to come from...) and then "Plugin Manager > Get More > install from url - https://github.com/awe-source/OctoPrint-SkipTo/archive/master.zip
> 
> ![image](https://private-user-images.githubusercontent.com/38069487/363163318-5f5cda24-5a0e-4443-8d30-6762c79afeb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjIxMzgsIm5iZiI6MTcyNTAyMTgzOCwicGF0aCI6Ii8zODA2OTQ4Ny8zNjMxNjMzMTgtNWY1Y2RhMjQtNWEwZS00NDQzLThkMzAtNjc2MmM3OWFmZWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEyNDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OTBhMmZjMWMwNjQ4ZmNhMDQzNjIzNTZlNTgxNzQ3ZGZmMjRiNjU4MjA0YjhkMzM3Y2MwOTM0ODY5ZjgyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l-R7RPQoZ3Nc9fDqV49LWwA575oIex9kpEjbhvHUAvc)

-using install from URL stopped the turning wheel but the problem persists.
-changing some settings worked until i restartet octoprint
-also i was unable to remove the plugin.
but, after several restarts of octoprint and the server i could remove it.

**Comment by awe-source** [comment]
Can you:
1.
Provide browser and version

2. 
Install/enable
Save a setting (eg change skip to screen to temp)
Try to skip to layer or z on any gcode file (if it works cancel asap...
And then goto
Settings
Logging 
Download the ocotprint log
And if you want just attach (or send us) the whole file or if not just the last 20-30 lines as long as you cancelled quickly 

Thanks and sorry u are experiencing this

**Comment by lebajez** [comment]
> Can you: 1. Provide browser and version
> 
ubuntu 22.04 snap for firefox
129.0.2(64bit)

> 
> Install/enable Save a setting (eg change skip to screen to temp) Try to skip to layer or z on any gcode file (if it works cancel asap... And then goto Settings Logging Download the ocotprint log And if you want just attach (or send us) the whole file or if not just the last 20-30 lines as long as you cancelled quickly
> 
> Thanks and sorry u are experiencing this

ad 2. sorry, but i have a long print running - i will get to this after the job has finished

**Comment by lebajez** [comment]
hi, i gave it another try.
it seems that, when i don't check-mark `Use Temp File`
 your plugin does work.
this is fine with me..
thank you
